apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: {{ include "mock-model.fullname" . }}
spec:
  predictors:
  - name: default
    replicas: {{ .Values.replicas }}
    componentSpecs:
    - spec:
        containers:
        - image: rafalskolasinski/mock-model:{{ .Values.version }}
          imagePullPolicy: IfNotPresent
          name: mock-model
          resources:
            requests:
              cpu: '{{ .Values.server.resources.requests.cpu }}'
              memory: '{{ .Values.server.resources.requests.memory }}'
            limits:
              cpu: '{{ .Values.server.resources.limits.cpu }}'
              memory: '{{ .Values.server.resources.limits.memory }}'
          env:
          - name: SELDON_LOG_LEVEL
            value: {{ .Values.server.logLevel | upper | quote }}
          - name: GUNICORN_WORKERS
            value: {{ .Values.server.workers | quote }}
          - name: GUNICORN_THREADS
            value: {{ .Values.server.threads | quote }}
    graph:
      type: MODEL
      name: mock-model
      {{- if .Values.enableLogging }}
      logger:
        mode: all
      {{- end}}
