apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: seldon-mock-model
  namespace: seldon
spec:
  predictors:
  - name: default
    replicas: 1
    componentSpecs:
    - spec:
        containers:
        - image: rafalskolasinski/mock-model:latest
          imagePullPolicy: IfNotPresent
          name: mock-model
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 1Gi
          env:
          - name: SELDON_LOG_LEVEL
            value: DEBUG
    graph:
      type: MODEL
      name: mock-model
