name: Build and push mock-model docker image

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  mock-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Commit
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push latest image
        working-directory: ./mock-model
        run: make image push

      - name: Build and push current dev
        working-directory: ./mock-model
        run: BASE_IMAGE_VERSION=1.14.0-dev IMAGE_VERSION=1.14.0-dev make image push

      - name: Build and push 1.13.1
        working-directory: ./mock-model
        run: BASE_IMAGE_VERSION=1.13.1 IMAGE_VERSION=1.13.1 make image push

      - name: Build and push 1.12.0
        working-directory: ./mock-model
        run: BASE_IMAGE_VERSION=1.12.0 IMAGE_VERSION=1.12.0 make image push

      - name: Build and push 1.11.2
        working-directory: ./mock-model
        run: BASE_IMAGE_VERSION=1.11.2 IMAGE_VERSION=1.11.2 make image push
