name: Build and push mock-model docker image

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  mock-model:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base:
        - "1.11.2"
        - "1.12.0"
        - "1.13.1"
        - "1.14.0"
        - "1.14.1"
        - "1.15.0-dev"
    steps:
      - name: Checkout Git Commit
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push latest image
        working-directory: ./mock-model
        run: make image push

      - name: Build and push image
        working-directory: ./mock-model
        run: BASE_IMAGE_VERSION=${{ matrix.base }} IMAGE_VERSION=${{ matrix.base }} make image push
